extern const GeoLayout Test_area_1_geo[];
extern const GeoLayout Test_area_1[];
extern const Collision Test_area_1_collision[];
extern const MacroObject Test_area_1_macro_objs[];
extern Lights1 Test_dl_f3dlite_material_001_lights;
extern Lights1 Test_dl_f3dlite_material_lights;
extern u8 Test_dl_wf_textures_05800_rgba16_ci8[];
extern u8 Test_dl_wf_textures_05800_rgba16_ci8_pal_rgba16[];
extern Vtx Test_dl_Cube_mesh_layer_1_vtx_0[5978];
extern Gfx Test_dl_Cube_mesh_layer_1_tri_0[];
extern Vtx Test_dl_Cylinder_mesh_layer_1_vtx_0[60];
extern Gfx Test_dl_Cylinder_mesh_layer_1_tri_0[];
extern Gfx mat_Test_dl_f3dlite_material_001[];
extern Gfx mat_revert_Test_dl_f3dlite_material_001[];
extern Gfx mat_Test_dl_f3dlite_material[];
extern Gfx mat_revert_Test_dl_f3dlite_material[];
extern Gfx Test_dl_Cube_mesh_layer_1[];
extern Gfx Test_dl_Cylinder_mesh_layer_1[];
extern Gfx Test_dl_material_revert_render_settings[];
